name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  dist:
    # Build the Python SDist and wheel, performs metadata and readme linting
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v2

  release:
    # Publish a GitHub release from the given git tag
    name: Create GitHub Release
    needs: [dist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

  publish:
    # Publish the built SDist and wheel from "dist" job on PyPI
    name: Publish to PyPI
    needs: [dist]
    runs-on: ubuntu-latest
    environment:
      name: Release
      url: https://pypi.org/project/linopy/
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
